import React, { useState } from 'react';
import JSEncrypt from 'jsencrypt';
import { Form, Button, Card, Row, Col } from 'react-bootstrap';
import Container from 'react-bootstrap/Container';

function Real() {
  const [message, setMessage] = useState('');
  const [publicKey, setPublicKey] = useState('');
  const [privateKey, setPrivateKey] = useState('');
  const [encryptedMessage, setEncryptedMessage] = useState('');
  const [decryptedMessage, setDecryptedMessage] = useState('');
  const [loading, setLoading] = useState(false);

  const generateKeys = () => {
    setLoading(true);
    const encrypt = new JSEncrypt({ default_key_size: 2048 });
    encrypt.getKey(() => {
      const publicKey = encrypt.getPublicKey();
      const privateKey = encrypt.getPrivateKey();
      setLoading(false);
      setPublicKey(publicKey);
      setPrivateKey(privateKey);
    });
  };

  const handleEncrypt = () => {
    const encrypt = new JSEncrypt();
    if (publicKey.length === 0) {
      alert("Public Key is empty. Please generate keys to proceed with encryption");
    } else {
      encrypt.setPublicKey(publicKey);
      if (message.length === 0) {
        alert("Input Message is empty. Please enter a message to encrypt");
      } else {
        const encrypted = encrypt.encrypt(message);
        setEncryptedMessage(encrypted);
      }
    }
  };

  const handleDecrypt = () => {
    const decrypt = new JSEncrypt();
    decrypt.setPrivateKey(privateKey);
    if (encryptedMessage.length === 0) {
      alert("Encrypted Message is empty.");
    } else {
      const decrypted = decrypt.decrypt(encryptedMessage);
      setDecryptedMessage(decrypted);
    }
  };

  return (

    <Container>
     <Row>    
       <Col>
   
      <Card border="light" className="customcardReal">
        <Card.Body>
          <Card.Title style={{ fontWeight: 'bold' }}>Key Generation</Card.Title>
          <Button onClick={generateKeys} disabled={loading}  variant="outline-info" className="mb-3">
            {loading ? 'Loading...' : 'Create Keys'}
          </Button>

          <Card.Text>
            <strong>Public Key:</strong>
            <div style={{ 
              background: '#f8f9fa', // Light gray background for better contrast
              padding: '10px', 
              borderRadius: '10px',
              color: '#333' // Dark text color for visibility
            }}>
              {publicKey || "Public Key will be autogenerated"}
            </div>
          </Card.Text>

          <Card.Text>
            <strong>Private Key:</strong>
            <div style={{ 
              background: '#f8f9fa', // Light gray background for better contrast
              padding: '10px', 
              borderRadius: '10px',
              color: '#333' // Dark text color for visibility
            }}>
              {privateKey || "Private Key will be autogenerated"}
            </div>
          </Card.Text>

          <Form className="customform mb-3">
            <Form.Label>Enter Message to encrypt:</Form.Label>
            <Form.Control
              type="text"
              placeholder="Enter Message"
              onChange={(e) => setMessage(e.target.value)}
            />
          </Form>

          <Button  onClick={handleEncrypt} variant="outline-info"  className="mb-3">
            Encrypt
          </Button>

          <Card.Text>
            <strong>Encrypted Message:</strong>
            <div style={{ 
              background: '#f8f9fa', // Light gray background for better contrast
              padding: '10px', 
              borderRadius: '10px',
              color: '#333' // Dark text color for visibility
            }}>
              {encryptedMessage || "Encrypted message will be autogenerated"}
            </div>
          </Card.Text>

          <Button onClick={handleDecrypt} variant="outline-info"  className="mb-3">
            Decrypt
          </Button>

          <Card.Text>
            <strong>Decrypted Message:</strong>
            <div style={{ 
              background: '#f8f9fa', // Light gray background for better contrast
              padding: '10px', 
              borderRadius: '10px',
              color: '#333' // Dark text color for visibility
            }}>
              {decryptedMessage || "Decrypted message will be autogenerated"}
            </div>
          </Card.Text>
          
        </Card.Body>
      </Card>
       </Col>   
      </Row>
    </Container>
  
  );
}

export default Real;
